-- Phase 4: Seed Agents from Spine

INSERT INTO agents (name, team, office, active) VALUES
    ('Alex', 'CSR', 'CH', true),
    ('Alexandra', 'CSR', 'MCM', true),
    ('Charmaine', 'Sales', 'MCM', true),
    ('Christian', 'Sales', 'MB', true),
    ('Claudia', 'Sales', 'RC', true),
    ('Danielle', 'EA', 'MCM', true),
    ('Dawn', 'CSR', 'MCM', true),
    ('Denice', 'CSR', 'MCM', true),
    ('Eddie', 'Sales', 'RC', true),
    ('Edwin', 'Sales', 'CH', true),
    ('Estela', 'CSR', 'RC', true),
    ('Frank', 'Sales', 'CH', true),
    ('Gabby', 'CSR', 'MCM', true),
    ('Gilda', 'EA', 'MCM', true),
    ('Giselle', 'EA', 'CH', true),
    ('Isabel', 'CSR', 'RC', true),
    ('Jenna', 'Sales', 'MB', true),
    ('Jerome', 'CSR', 'CH', true),
    ('Jessie', 'Sales', 'MCM', true),
    ('Jonathan', 'Sales', 'MB', true),
    ('Jose', 'CSR', 'MB', true),
    ('Juanita', 'CSR', 'MB', true),
    ('Liliana', 'CSR', 'RC', true),
    ('Lori', 'CSR', 'MCM', true),
    ('Maila', 'CSR', 'RC', true),
    ('Misty', 'EA', 'MCM', true),
    ('Rosalba', 'Sales', 'RC', true),
    ('Rosie', 'CSR', 'MB', true),
    ('Roxana', 'EA', 'CH', true),
    ('Suzanne', 'EA', 'MCM', true),
    ('Sylvia', 'EA', 'RC', true),
    ('Teyssy', 'CSR', 'CH', true),
    ('Zypher', 'Sales', 'MCM', true),
    ('Ariana', 'Sales', 'RC', true),
    ('Danny', 'Sales', 'CH', true),
    ('Nancy', 'CSR', 'MB', true),
    ('Robert', 'Sales', 'MB', true),
    ('Hrach', 'Sales', 'MCM', true),
    ('Chris', 'Sales', 'MCM', true),
    ('Elizabeth', 'CSR', 'MCM', true)
ON CONFLICT (name) DO UPDATE SET team = EXCLUDED.team, office = EXCLUDED.office, active = EXCLUDED.active;
